export const EN = {
  login: 'Log in',
  logging: 'Logging in...',
  logout: 'Log out',
  register: 'Register',
  registration: 'Registration...',
  registered: 'Already registered?',
  addPlace: 'New place',
  placeName: 'Name',
  placeLink: 'Picture link',
  createBtn: 'Create',
  editProfile: 'Edit profile',
  profileName: 'Your name',
  profileAbout: 'About you',
  saveBtn: 'Save',
  saving: 'Saving...',
  updateAvatar: 'Update avatar',
  avatarLink: 'Avatar link',
  confirmQuestion: 'Are you sure?',
  confirm: 'Yes',
  removing: 'Removing...',
  isSignup: 'Registration is successfully!',
  password: 'Password',
  notFoundErr: 'Data not found',
  badRequestErr: 'Invalid data',
  conflictErr: 'This email already exists',
  forbiddenErr: 'No rights for this action',
  authErr: 'Invalid email or password',
  serverErr: 'Server error',
  pathNotFound: 'Path not found',
  unauthorized: 'Authorisation is required'
}

export const RU = {
  login: 'Вход',
  logging: 'Вход...',
  logout: 'Выйти',
  register: 'Зарегистрироваться',
  registration: 'Регистрация...',
  registered: 'Уже зарегистрированы?',
  addPlace: 'Новое место',
  placeName: 'Название',
  placeLink: 'Ссылка на картинку',
  createBtn: 'Создать',
  editProfile: 'Редактировать профиль',
  profileName: 'Имя',
  profileAbout: 'О себе',
  saveBtn: 'Сохранить',
  saving: 'Сохранение...',
  updateAvatar: 'Обновить аватар',
  avatarLink: 'Ссылка на картинку',
  confirmBtn: 'Вы уверены?',
  confirm: 'Да',
  removing: 'Удаление...',
  isSignup: 'Вы успешно зарегистрировались!',
  password: 'Пароль',
  notFoundErr: 'Data not found',
  badRequestErr: 'Данные не найдены',
  conflictErr: 'Такой email уже существует',
  forbiddenErr: 'Нет прав для данного действия',
  authErr: 'Некорректный email или пароль',
  serverErr: 'Произошла ошибка на сервере',
  pathNotFound: 'Путь не найден',
  unauthorized: 'Необходима авторизация'
}